version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run: docker-compose -f ~/project/2/app.yml build
  api-test:
    docker:
      - image: circleci/node:8.11.1
    steps: 
      - checkout
      - run: pwd && ls
      - run: make test-api
  chess-test:
    docker:
      - image: circleci/node:8.11.1
    steps: 
      - checkout
      - run: pwd && ls
      - run: make test-chess -C ./2/
  auth-test:
    docker:
      - image: circleci/node:8.11.1
    steps: 
      - checkout
      - run: make test-auth

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - api-test:
        requires:
          - build
      - chess-test:
        requires:
          - build
      - auth-test:
        requires:
          - build