version: 2
jobs:
  api-test:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/project/3/api/api
    steps: 
      - checkout:
          path: ~/project/
      - run: npm install
      - run: npm test
  chess-test:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/project/3/chess/chess
    steps: 
      - checkout:
          path: ~/project/
      - run: npm install
      - run: npm test
  auth-test:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/project/3/auth/auth
    steps: 
      - checkout:
          path: ~/project/
      - run: npm install
      - run: npm test

#CircleCI uses an OR operator on filters
#In order to only build on tagged releases we need to ignore all branches
#OR filter by tag... feels hacky
workflows:
  version: 2
  build-and-test:
    jobs:
      - api-test
      - auth-test
      - chess-test