version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run: docker-compose -f ~/project/2/app.yml build
  api-test:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/project/2/api/api
    steps: 
      - checkout:
          path: ~/project/
      - run: npm install
      - run: npm test
  chess-test:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/project/2/chess/chess
    steps: 
      - checkout:
          path: ~/project/
      - run: npm install
      - run: npm test
  auth-test:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/project/2/auth/auth
    steps: 
      - checkout:
          path: ~/project/
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - api-test
      - chess-test
      - auth-test
      - build:
          requires:
            - apt-test
            - chess-test
            - auth-test