version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run: docker-compose -f ~/project/2/app.yml build
  test:
    docker:
      - image: circleci/classic:edge
    steps:
      - checkout
      - run: ~/project/2/make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build