apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: simpsonjon/chessplat:auth
        name: auth
        ports:
        - containerPort: 3000
      restartPolicy: Always
