apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: chess-d
spec:
  selector:
    matchLabels:
      app: chess
  replicas: 1
  template:
    metadata:
      labels:
        app: chess 
    spec:
      volumes:
        - name: chess-cred
          secret:
            secretName: chess-cred
      containers:
      - image: simpsonjon/chessplat:chess
        name: chess
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: chess-cred
          readOnly: true
          mountPath: "/secret/"
        env:
        - name: PROJNAME
          value: "simpsonjon-remote" 
        - name: TOPICNAME
          value: "chess-moves"
        - name: NAMESPACE
          value: "testing"
      restartPolicy: Always