version: "3.4"
services:
  api:
    build: 
      context: ./api
      dockerfile: Test.Dockerfile
      target: dev 
    image: simpsonjon/chessplat:api-test
    volumes:
      - ./api/api:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - PROJNAME=fauxpassproj-dev
      - TOPICNAME=chess-moves
    links:
      - auth
      - chess
  auth:
    build: 
      context: ./auth
      dockerfile: Test.Dockerfile
      target: dev
    image: simpsonjon/chessplat:auth-test
    volumes: 
      - ~/.config/:/root/.config
      - ./auth/auth:/app
      - /app/node_modules
    ports:
      - 8080:3000

  chess:
    build: 
      context: ./chess
      dockerfile: Test.Dockerfile
      target: dev
    image: simpsonjon/chessplat:chess-test
    volumes:
      - ~/.config/:/root/.config
      - ./chess/chess:/app
      - /app/node_modules
    ports:
      - 8081:3000
    environment:
      - SUBNAME=moves
      - PROJNAME=fauxpassproj-dev
  