version: "2"
services:
  api:
    build: ./api
    image: simpsonjon/chessplat:api
    ports:
      - 3000:3000
    links:
      - auth
      - chess
  auth:
    build: ./auth
    image: simpsonjon/chessplat:auth
    ports:
      - 8080:3000

  chess:
    build: ./chess
    image: simpsonjon/chessplat:chess
    ports:
      - 8081:3000
  
  integration:
    build: ./integration
    image: simpsonjon/chessplat:integration-test
    environment:
      - API_HOST=api
      - API_PORT=3000
    links:
      - api